name: run main.py

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - uses: ryan-rozario/pipreqs-action-cpy@master

        # Put an example of mandatory inputs here
        with:
          PROJECT_PATH: .   #default is the root of the repository
          REQUIREMENT_PATH: ./requirements.txt  #default is requirement.txt in the root of your repository

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        run: python main.py

